# Generated by Django 3.2 on 2021-08-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Possition', models.CharField(max_length=50)),
                ('ClientImage', models.ImageField(upload_to='Startup/Client')),
                ('Feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Startup/ClientLogo')),
            ],
        ),
    ]
