# Generated by Django 3.2 on 2021-08-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_clientfeedback_feedback_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='ClientImage',
            new_name='Client_Image',
        ),
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='ClientName',
            new_name='Client_Name',
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='Feedback_Star',
            field=models.CharField(choices=[('1', '1 star'), ('2', '2 star'), ('3', '3 star'), ('4', '4 star'), ('5', '5 star')], default=4, max_length=1),
        ),
    ]
