# Generated by Django 3.2 on 2021-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20210813_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='Feedback_Star',
            field=models.CharField(choices=[('1', '1 star'), ('2', '2 star'), ('3', '3 star'), ('4', '4 star'), ('5', '5 star')], default=5, max_length=1),
        ),
    ]
