# Generated by Django 3.2 on 2021-08-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.SlugField(unique=True)),
                ('Category', models.CharField(max_length=50)),
                ('Client', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Startup/Project')),
                ('Description', models.TextField()),
            ],
        ),
    ]
