# Generated by Django 3.2 on 2021-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210814_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Slug',
            new_name='slug',
        ),
    ]
