# Generated by Django 3.2 on 2021-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('msg', models.TextField()),
            ],
        ),
    ]
