# Generated by Django 3.2 on 2021-08-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Slug', models.SlugField(unique=True)),
                ('ShortDes', models.CharField(max_length=250)),
                ('ServiceImage', models.ImageField(upload_to='Startup/Service')),
                ('Service_Hover_Image', models.ImageField(upload_to='Startup/Service')),
                ('Description', models.TextField()),
            ],
        ),
    ]
