# Generated by Django 3.2 on 2021-08-13 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Category',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
