# Generated by Django 3.2 on 2021-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_slug_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Service_Details_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Startup/Service'),
        ),
    ]
