# Generated by Django 3.2 on 2021-08-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogpost_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Slug',
            new_name='slug',
        ),
    ]
