# Generated by Django 3.2 on 2021-08-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Role', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Startup/Team')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Media_Name', models.CharField(max_length=50)),
                ('Social_Media_link', models.CharField(max_length=250)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About.teammember')),
            ],
        ),
    ]
