# Generated by Django 3.2 on 2021-08-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='SocialLink',
        ),
    ]
